### ISSUE TITLE
Texture issue

### ISSUE THREAD

**Issue by mitchngwen** [ItemsAdder/DefaultPack#12]
Why is this happening with the defaultpack?

![Screenshot_20220717_214806](https://user-images.githubusercontent.com/45637150/179442614-4c0553fe-2fab-4fb8-a548-bad3b9273724.png)

**Comment by LoneDev6** [comment]
This doesn't look like the default pack.
You have some other items.

Check your server logs and your CLIENT logs ([read here](https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#enable-output-log)) in order to identify which files are causing the resourcepack to fail loading the items textures.

(This is not caused by ItemsAdder itself or by the default pack)
